checkTx endpoint changed to checkTxs
EdgeApp/edge-reports-server pull request #94
Opened 2020-11-24 23:43 UTC by thomasgonda3

2020-11-25 22:40 UTC, thomasgonda3 commented on src/indexApi.ts
> +interface CheckTxs {
interface checkTxsResponse

2020-11-25 22:40 UTC, thomasgonda3 commented on src/indexApi.ts
> +interface CheckTxs {
Check

2020-11-25 22:43 UTC, thomasgonda3 commented on src/indexApi.ts
> +      apiKey: asString,
move apiKey outside of each individual tx, and check it only once.

2020-11-25 22:43 UTC, thomasgonda3 commented on src/indexApi.ts
> +  appId?: string
appId is returned outside of array of responses.

2020-11-25 22:48 UTC, thomasgonda3 commented on src/indexApi.ts
> +        data.push(returnTx)
apiKey if wrong should throw whole thing

2020-11-25 22:49 UTC, thomasgonda3 commented on src/indexApi.ts
> +        const dbResult = await reportsTransactions.get(query)
should be bulk get

2020-11-25 22:49 UTC, thomasgonda3 commented on src/indexApi.ts
> +        const dbResult = await reportsTransactions.get(query)
in batches of 100

2020-12-02 02:04 UTC, paullinator requested changes
See comments. As well, please squash all commits into one for this pr.

2020-12-02 02:04 UTC, paullinator commented on src/indexApi.ts
> +const asCheckTxsServerResponse = asArray(
This really should be `asTxFetch`. This is not a server response but rather the response of the database.

2020-12-02 02:04 UTC, paullinator commented on src/indexApi.ts
> +        counter + CHECKTXS_BATCH_LIMIT
The batching is supposed to be enforced at the API level meaning the utility server should send no more than 100 order IDs to the report server. Within the checkTxs endpoint, you do not need to batch queries to the database. However you should throw a 400 error if the caller sends more than 100 order IDs.

2020-12-03 19:30 UTC, paullinator approved these changes

2020-12-03 19:31 UTC, merged